---
- name: trust weechat repo key
  apt_key:
    id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E
    keyserver: hkps://keys.openpgp.org
    state: present

- name: add weechat repository
  apt_repository:
    repo: deb https://weechat.org/debian buster main
    state: present
    filename: weechat

- name: install weechat and plugins
  apt:
    name:
      - weechat-curses
      - weechat-plugins
      - weechat-python
      - weechat-perl
      - python3-websocket  # for weeslack

# Pretty unstable, sometimes segfault and compilation often broken
# - import_tasks: ripgrep_weechat.yml

- import_tasks: matrix_weechat.yml

- import_tasks: tmux_weechat.yml
