- name: restart the RI notify bot (post watcher)
  listen: ri notify restart
  systemd:
    name: badeconomics-ri-notify.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart the RI notify bot (command watcher)
  listen: ri notify restart
  systemd:
    name: badeconomics-ri-command.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart the HOA timer
  listen: hoa restart
  systemd:
    name: badeconomics-hoa.timer
    daemon_reload: true
    enabled: false  # Disabled for the time being
    state: stopped
