---
- name: install base packages
  apt:
    name:
      - aptitude
      - curl
      - git
      - gpg
      - htop
      - man
      - postgresql
      - python3
      - python3-apt
      - python3-dev
      - python3-psycopg2
      - python3-venv
      - rsync
      - sudo
      - vim
      - zsh
    update_cache: yes

- name: add seirl user
  user:
    name: seirl
    comment: Antoine Pietri
    shell: /bin/zsh
    group: seirl
    groups:
      - seirl
      - users
      - sudo
    append: yes

- name: add seirl postgresql user
  postgresql_user:
    name: seirl
    role_attr_flags: SUPERUSER,CREATEDB
  become: true
  become_user: postgres

- name: update hosts file
  template:
    src: 'hosts'
    dest: '/etc/hosts'
