---
- name: install base packages
  apt:
    name:
      - aptitude
      - curl
      - dnsutils
      - fail2ban
      - git
      - git-extras
      - gpg
      - htop
      - mosh
      - man
      - postgresql
      - python3
      - python3-apt
      - python3-dev
      - python3-psycopg2
      - python3-venv
      - reptyr
      - rsync
      - sudo
      - tmux
      - vim
      - zsh
    update_cache: yes

- name: add backports repository
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    filename: weechat

- name: add seirl user
  user:
    name: seirl
    comment: Antoine Pietri
    shell: /bin/zsh
    group: seirl
    groups:
      - seirl
      - users
      - sudo
    append: yes

- name: add seirl postgresql user
  postgresql_user:
    name: seirl
    role_attr_flags: SUPERUSER,CREATEDB
  become: true
  become_user: postgres

- name: update hosts file
  template:
    src: 'hosts'
    dest: '/etc/hosts'

- name: Create persistent log directory
  file:
    path: /var/log/journal
    state: directory
